services:
  version: "3"
services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - drift-network
    restart: always
    environment:
      PRODUCTION: "false"
      PORT: 8080
      LOG_LEVEL: "debug"
      DISCORD_API: ""
      DISCORD_CLIENT_ID: ""
      DISCORD_SECRET: ""
      DISCORD_REDIRECT_URI: ""
      DISCORD_GENERATED_URL: ""
      CLIENT_URL: "http://localhost:3000"
      DRIFT_MESSAGE: "Default Message"
      GCP_CLOUD_SQL_INSTANCE: ""
      MYSQL_HOST: "localhost"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "dev"
      MYSQL_DB: "drift-discord"
      AES_HTTP_TRANSPORT_SECRET: ""
    depends_on: 
      - db
  # client:
  #   container_name: client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - drift-network
  #   restart: always
  #   depends_on:
  #     - api
  #   restart: always
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_DATABASE: "drift-discord"
    networks:
      - drift-network
    
networks:
  drift-network:
    driver: bridge