services:
  version: "3"
services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - drift-network
    restart: always
  environment:
    PORT=8080
    MONGO_CONN_STRING=
    DISCORD_API=
    DISCORD_CLIENT_ID=
    DISCORD_SECRET=
    DISCORD_REDIRECT_URI=
    DRIFT_MESSAGE=
    CLIENT_URL=
    AES_HTTP_TRANSPORT_SECRET=
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - drift-network
    restart: always
    depends_on:
      - api
    restart: always
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - drift-network
networks:
  drift-network:
    driver: bridge