apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: gcr.io/drift-discord/api:0.0.1
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-east1
  name: api
  namespace: '326234874656'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '2'
        client.knative.dev/user-image: gcr.io/drift-discord/api:0.0.1
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 392.0.0
      name: api-00016-ram
    spec:
      containerConcurrency: 100
      containers:
      - image: gcr.io/drift-discord/api:0.0.1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
      serviceAccountName: 326234874656-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
