export const DISCORD_GENERATED_URL: string =
  'https://discord.com/api/oauth2/authorize?client_id=997668769570750524&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fv1%2Fdiscord_redirect&response_type=code&scope=identify%20email' // not a secret...
export const DRIFT_MESSAGE: string = `Welcome to Drift Discord! Drift’s goal is to bring a state-of-the-art trader-centric experience from centralized exchanges on-chain. We're a team of experienced traders and builders from DeFi and traditional finance working together to make this a reality.`
