# Development SQL instance.
services:
  version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_DATABASE: "drift-discord"
    ports: 
      - 3306:3306
networks:
  drift-network:
    driver: bridge