steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/${_GCP_PROJECT}/${_SERVICE_NAME}:${_SERVICE_VERSION}',
        '${_SOURCE_PATH}',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'gcr.io/${_GCP_PROJECT}/${_SERVICE_NAME}:${_SERVICE_VERSION}']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${_GCP_PROJECT}/${_SERVICE_NAME}:${_SERVICE_VERSION}'
      - '--region'
      - '${_GCP_REGION}'
      - '--platform'
      - 'managed'
      - '--cpu'
      - '${_CPUS}'
      - '--concurrency'
      - '${_CONCURRENCY}'
      - '--memory'
      - '${_MEMORY}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--allow-unauthenticated'
    env:
      - 'PORT=8080'
      - 'DISCORD_API=https://discord.com/api/v8'
      - 'CLIENT_URL=https://client-4fpiw4senq-ue.a.run.app'
      - 'DRIFT_MESSAGE=Welcome to Drift Discord! Drift’s goal is to bring a state-of-the-art trader-centric experience from centralized exchanges on-chain.'
      - 'DISCORD_REDIRECT_URI=TODO AFTER SUCCESSFUL DEPLOY'
      - 'DISCORD_GENERATED_URL=TODO AFTER SUCCESSFUL DEPLOY'
    secretEnv: ['MONGO_CONN_STRING', 'DISCORD_CLIENT_ID', "DISCORD_SECRET", "AES_HTTP_TRANSPORT_SECRET"]

images:
  - 'gcr.io/${_GCP_PROJECT}/${_SERVICE_NAME}:${_SERVICE_VERSION}'

timeout: 1800s

substitutions:
  _SOURCE_PATH: './api'
  _GCP_PROJECT: 'drift-discord'
  _GCP_REGION: 'us-east1'
  _SERVICE_NAME: 'api'
  _SERVICE_VERSION: '0.0.1'
  _MEMORY: '1Gi'
  _CPUS: '1'
  _CONCURRENCY: '100'
  _MAX_INSTANCES: '2'
  # _PORT: '8080'
  # _DISCORD_API: 'https://discord.com/api/v8'
  # _CLIENT_URL: 'https://client-4fpiw4senq-ue.a.run.app'
  # _DRIFT_MESSAGE: 'Welcome to Drift Discord! Drift’s goal is to bring a state-of-the-art trader-centric experience from centralized exchanges on-chain.'
  # _DISCORD_REDIRECT_URI: "TODO AFTER SUCCESSFUL DEPLOY"
  # _DISCORD_GENERATED_URL: "TODO AFTER SUCCESSFUL DEPLOY"
availableSecrets:
  secretManager:
  - versionName: 'projects/326234874656/secrets/MONGO_CONN_STRING/versions/1'
    env: 'MONGO_CONN_STRING'
  - versionName: 'projects/326234874656/secrets/DISCORD_CLIENT_ID/versions/1'
    env: 'DISCORD_CLIENT_ID'
  - versionName: 'projects/326234874656/secrets/DISCORD_SECRET/versions/1'
    env: 'DISCORD_SECRET'
  - versionName: 'projects/326234874656/secrets/AES_HTTP_TRANSPORT_SECRET/versions/1'
    env: 'AES_HTTP_TRANSPORT_SECRET'